#!/usr/bin/python
# -*- coding: utf-8 -*-
# *****************************************************************************
# Host          : sarbecovirus
# File          : gensjw.py
# Author        : ALX
# Creation      : 2020-07-13
# Last Revision : 2020-07-18
# Release       : V1.02
# Description   : Générateur SJW
# *****************************************************************************

import os, sys
import random

intro = ["Salut vieille branche",
         "Une question me turlupine le ciboulot",
         "J'avoue",
         "Qu'ouïe-je ?",
         "Salut, ça boume ?",
         "Où avais-je la tête ?",
         "Nan mais allô quoi !",
         "Je vais être franc du collier : "
         "C'est parti mon kiki",
         "Tchin tchin !",
         "Laisse béton",
         "Tout doux bijou !",
         "Te fais pas de mouron",
         "Cours Forrest !",
         "Même pas cap !",
         "Quote quote kodak !",
         "Qu'à cela ne tienne !",
         "En voiture Simone",
         "Salut les jeunes",
         "Salut la jeunesse",
         "Oki doki",
         "Salut, ça gaze ?",
         "Mollo l'asticot",
         "Allô ! À l'huile !",
         "Salut, ça farte ?",
         "Tiens, en v'là un qui déboule !",
         "Salut les filles, on se retrouve sur Minitel ?",
         "Excuse moi, mais ça me fait doucement rire !",
         "Hep ! Qui va là ?",
         "Bonjour tout le monde ! Salut tout seul",
         "Allons-y, Alonso !",
         "Je donne ma langue aux chats",
         "Tu me poses une colle",
         "Sacré nom d'une pipe",
         "Minute papillon",
         "Salut, ça farte ?",
         "Alors, on n'attend pas Patrick ?",
         "Beh dis donc, toi, tu laisse pas ta part au chien",
         "C'est bigrement important",
         "Turlututu chapeau pointu",
         "Ben dis donc",
         "Chouette, mets tes basquettes"]

imperatif = ["Tape dans l'fond, j'suis pas ta mère",
             "Pète un coup, ça ira mieux !",
             "Va te faire cuire un oeuf",
             "Mouche ton nez, tu diras bonjour à la dame après",
             "Ferme ta boite à camembert",
             "Va te faire cuire un oeuf",
             "Ramène ta fraise",
             "Viens faire la nouba",
             "Parle à ma main"]

prop_je = ["Je me fais bien du tracas",
           "Je me suis cassé la binette",
           "Je suis sur la sellete",
           "Je vais te remonter les bretelles",
           "Je te conseille de donner un coup de collier",
           "Je suis tombé dans les pommes",
           "Je suis rond comme une queue de pelle",
           "Je te vois venir avec tes gros sabots",
           "Je me porte comme un charme",
           "Je me mets sur mon trente et un",
           "Je suis revenu bredouille",
           "Je compte pour du beurre ?",
           "Je ne vais pas tourner autour du pot",
           "Je vais te faire courir, rouquin",
           "J'ai le cigare au bord des lèvres",
           "J'ai les dents du fond qui baignent",
           "J'ai vu ta mère sur chatroulette !",
           "J'ai pissé dans mon froc",
           "J'ai l'estomac dans les talons",
           "J'ai un poil dans la main",
           "J'ai pris la tangente",
           "J'ai découvert le pot aux roses",
           "J'ai le persil qui dépasse du cabas",
           "J'ai bien envie de lui casser ses petites pattes arrière",
           "J'ai la taupe au guichet",
           "J'ai les dents du fond qui baignent",
           "J'peux pas, j'ai aqua-poney",
           "J'aimerais être ton gant de toilette",
           "J'en ai vu des vertes et des pas mûres",
           "J'en ai ma claque !",
           "La moutarde me monte au nez"]

prop_tu = ["Tu me portes la scoumoune",
           "Tu t'es vu quand t'as bu",
           "Tu me racontes des boniments",
           "Tu as semé la zizanie",
           "Tu a le vent en poupe",
           "Tu veux ma photo, tête de crapaud ? Tu l'auras pas, face de rat !",
           "Tu es allumé du ciboulot !",
           "Tu as un pois chiche à la place du cerveau",
           "Tu as la pêche !",
           "Tu peux dormir sur tes deux oreilles",
           "Tu as une descente, j'aimerais pas me la faire à pieds",
           "Tu as la tête sur les épaules",
           "Tu as une case en moins",
           "Tu es mou comme une chique",
           "Tu as le compact disc qui tourne à l'envers",
           "Tu t'es coiffé avec le loquet de la porte",
           "Tu serais pas de la jaquette, toi ?",
           "Tu vas te faire remonter les bretelles",
           "Tu as mis le feu aux poudres",
           "Tu es un coutumier du fait",
           "Tu prends des vessies pour des lanternes",
           "Tu as un nom à coucher dehors",
           "Tu me racontes des salades",
           "Tu ne sembles pas casser quatre pattes à un canard",
           "Tu vas passer incognito",
           "Tu bottes en touche",
           "Tu me cherches des noises",
           "Tu me cherches des poux",
           "Tu as la science infuse",
           "Tu vas mordre la poussière",
           "Tu m'en fais voir des vertes et des pas mûres",
           "Tu jettes l'argent par les fenêtres",
           "T'as les boules, t'as les glandes, t'as les crottes de nez qui pendent",
           "T'as pas inventé la machine à cintrer les bananes",
           "T'as les pétoches",
           "Toi, tu n'as pas la langue dans ta poche",
           "T'es pas la moitié d'un con",
           "T'es un peu soupe au lait, toi, non ?",
           "Toi, tu as la morteautitude !",
           "Et toi, t'es sur face de bouc ?",
           "Si t'as signé, c'est pour en chier !",
           "Peux-tu éclairer ma lanterne ?",
           "Jeune, qu'à tu sur la patate ?",
           "Où as-tu trouvé ton permis de conduire ? Dans une pochette surprise ?",
           "Ca roule ?",
           "Mieux vaut t'avoir en photo qu'en pension",
           "Ton père est un voleur. Il a pris toutes les étoiles du ciel pour les mettre dans tes yeux"]

prop_ca = ["Ca ne va pas te boucher le trou de balle",
           "Ca sent le sapin",
           "Ca te dérange, tête d'orange ?",
           "Ca chie dans le ventilo"
           "Ca commence à me courir sur le haricot",
           "Ca roulotte ?",
           "Ca m'a donné du fil à retordre",
           "Ca t'dérange, tête d'orange ? Tu t'l'épluche et tu la manges !",
           "Ca va jaser dans les chaumières",
           "C'est parti comme sur des roulettes",
           "C'est la fin des haricots",
           "C'est comme le porc salut, c'est écrit dessus",
           "C'est une autre paire de manches",
           "C'est une situation cocasse",
           "C'est la fête du slip",
           "C'est pas la mer à boire",
           "C'est comme si je pissais dans un violon",
           "Ce n'est pas de la petite bière",
           "Ce n'est pas à un vieux singue que l'on apprend à faire des grimaces",
           "Fait chaud comme une baraque à frites !",
           "Cette descente, j'aimerais pas la remonter à vélo",
           "Il n'y a pas péril en la demeure",
           "Il fait noir comme dans le cul d'un singe",
           "Il ne faudrait pas tuer la poule aux oeufs d'or",
           "Il a free, il  a tout compris",
           "Il pleut des cordes",
           "Il fait un froid de canard !",
           "Y'a de la meuf",
           "Il ne faudrait pas pousser mamie dans les orties",
           "Elle m'a fait du gringue",
           "Elle m'a posé un lapin",
           "Les dés sont pipés"]

prop_on = ["On s'bigophone ?",
           "On se fend la poire",
           "On ne va pas chercher midi à quatorze heure",
           "On va tellement te chier dans les bottes que t'auras plus de place pour y mettre tes pieds",
           "On n'est pas là pour trier les lentilles",
           "On s'épile, on s'fait une touffe",
           "On n'arrête pas le progrès",
           "On va remettre les pendules à l'heure.",
           "On s'entend comme larrons en foire",
           "On n'a pas élevé les cochons ensemble",
           "On a du pain sur la planche",
           "On es partis sur des chapeaux de roue",
           "On va casser la graine ?",
           "On n'est pas venus ici déguisés en pinguins pour se taper le cul sur la banquise",
           "On ne va pas se disputer pour des peccadilles",
           "Qu'est-ce qu'on fait ? On fait bli"]

conclusion = ["À bon entendeur, salut",
              "Quelle affaire !",
              "Bon allez ! Coucouche panier !",
              "Enfin j'dis ça, j'dis rien",
              "J'en suis fort aise",
              "Ca frise le ridicule",
              "C'est tout de même pas la mer à boire",
              "C'est peanuts !",
              "À la bonne heure !",
              "Je ne mange pas de ce pain là",
              "En avant Guingamp",
              "Je m'en tamponne le coquillard !",
              "Dans l'cul Lulu",
              "Ou pas !",
              "Y'à pas de quoi vermifuger un abribus",
              "On ne va pas en faire tout un fromage",
              "Roulez jeunesse !",
              "À plus dans l'bus",
              "Roule ma poule",
              "Au temps pour moi.",
              "Ca me turlupine",
              "Ca me fait chavirer du noeud papillon !",
              "Tu vas pas nous en chier une pendule !",
              "L'affaire est entendue",
              "Ca ne mange pas de pain",
              "Banco, on vend la caravanne",
              "Rira bien qui rira le dernier",
              "On s'textotte ?",
              "Dans le cul Lulu",
              "C'est la poêle qui se fout du chaudron",
              "Pas folle la guèpe !",
              "C'est pas ma came",
              "C'est une affaire qui roule"]

exclamation = ["C'est bath !",
               "C'est tip-top moumoute !",
               "C'est la classe à Dallas",
               "C'est le pompon sur la garonne",
               "C'est la faute à pas de chance",
               "C'est chanmax !",
               "C'est pas la foire à la saucisse",
               "C'est plus fort que du Roquefort",
               "C'est trop la latche !",
               "C'est ringardos !",
               "C'est d'enfer",
               "C'est trop swag !",
               "C'est la loose à Toulouse",
               "C'est stylé",
               "C'est le turfu !",
               "C'est rocambolesque",
               "C'est trop chanmé !",
               "C'est giga tip-top !",
               "C'est sensass",
               "C'est tip top",
               "Ca envoie du pâté",
               "Ca va chier des bulles",
               "Ca craint du boudin",
               "Ca c'est fort de café",
               "Ca va chier des marmottes",
               "Chic !",
               "Enfer et damnation !",
               "Par la barbe de saint-Michel !",
               "Ca l'fait !",
               "Chiotte à cul !"
               "Un peu mon n'veu !",
               "Des clous !",
               "Nickel chrome !"
               "Diantre !",
               "Bordel à cul !",
               "Fichtre !",
               "Ventre-saint-gris",
               "Sacré nom d'une pipe !",
               "Nom d'une pipe en bois",
               "Saperlipopette",
               "Bigre !",
               "Parbleu",
               "Sacrebleu",
               "Kikou... lol",
               "Nom d'un petit bonhomme",
               "Tu m'étonnes Ayrton",
               "Non de bleu",
               "Olala",
               "Et Patati patata",
               "Oh, non de Dieu",
               "Trop d'la boule",
               "Ca glousse !",
               "Trop d'la balle",
               "Ca décoiffe !",
               "tip top",
               "Quelle gabegie !",
               "C'est chouette !",
               "Sacre bleu",
               "Diantre",
               "Mazette",
               "la poilade",
               "Nom d'un chien !",
               "Quelle guigne !",
               "Ciel !",
               "Pardi !",
               "Mais quelle barbe...",
               "À bon entendeur, salut !",
               "Crotte de bique !",
               "Par ici la musique",
               "Pouet pouet camembert !",
               "Ouste ! Du balai !",
               "Bon sang de bonsoir !",
               "Je like"]

diminutif = ["ma caille",
             "loustic",
             "va-nu-pieds"
             "fripouille"]

comment = ["avec ceinture et bretelles"
           "à qui mieux mieux",
           "à toute berzingue !",
           "à la saint-Glinglin",
           "au petit bonheur la chance",
           "à tour de rôle",
           "illico presto",
           "à la queue leu leu",
           "plein comme une oeuf",
           "le cul entre deux chaises",
           "du tac o tac",
           "à la va comme je te pousse",
           "en bonne et due forme",
           "avec le dos de la cuillère",
           "autant que faire se peut",
           "les doigts dans le nez"]

adj = ["ficellé comme un rôti",
       "idoine",
       "branchouille",
       "pédé comme un foc",
       "qui ne mange pas de pain",
       "haut comme trois pommes",
       "la gueule enfarinée",
       "blanc comme un drap",
       "rouge comme une tomate",
       "vert de jalousie",
       "aimable comme un trou de chiotte",
       "aimable comme une porte de prison",
       "poilant"]

quoi = ["la rock'n roll attitude"
        "un lecteur cassette",
        "un walkman",
        "une corbeille à papier",
        "le change-chaîne",
        "un minitel",
        "des sandalettes",
        "un sac de noeuds",
        "la pistoche",
        "des balivernes",
        "une tripotée",
        "un tricot de peau",
        "un fil conducteur"]

qui = ["un loubard",
       "un loustic",
       "un disque jockey",
       "une tête de linotte",
       "un ours mal lêché",
       "un garnement",
       "un gredin",
       "un énergumène",
       "un trublion",
       "un bandit de grand chemin",
       "un bout-en-train",
       "un malautru",
       "un vioc",
       "un joyeu drille",
       "un gai luron"]

dicton = ["Pastis par temps bleu, pastis délicieux !",
          "Après la pluie vient le beau temps",
          "Eté en Août, pâté en croûte",
          "Pierre qui roule n'amasse pas mousse",
          "Il n'y a pas de fumée sans feu",
          "Les carottes sont cuites",
          "Chacun voit midi à sa porte",
          "Le chien aboie, la caravanne passe",
          "Messieurs les anglais, tirez les premiers",
          "Mieux vaut un coca aux glaçons qu'un caca collé au caleçon",
          "Santé ! Mais pas des pieds",
          "Chacun chez soi et les cochons seront bien gardés",
          "Avec des si, on mettrait Paris en bouteille",
          "Et comme on dit par chez moi : un tiens vaut mieux que deux tu l'auras."]

ou = ["de France et de Navarre",
      "à pétaochnoque",
      "à perpette les olivettes"]

principale = ["Il y a belle lurette que",
              "Je subodore que ",
              "Je mets ma main au feu que"]

random.seed()

intro1 = intro [random.randint(0,len(intro)-1)]
imperatif1 = imperatif [random.randint(0,len(imperatif)-1)]
prop_je1 = prop_tu [random.randint(0,len(prop_tu)-1)]
prop_tu1 = prop_tu [random.randint(0,len(prop_tu)-1)]
prop_ca1 = prop_ca [random.randint(0,len(prop_ca)-1)]
prop_on1 = prop_on [random.randint(0,len(prop_on)-1)]
conclusion1 = conclusion [random.randint(0,len(conclusion)-1)]
exclamation1 = exclamation [random.randint(0,len(exclamation)-1)]
diminutif1 = diminutif [random.randint(0,len(diminutif)-1)]
comment1 = comment [random.randint(0,len(comment)-1)]
adj1 = adj [random.randint(0,len(adj)-1)]
quoi1 = quoi [random.randint(0,len(quoi)-1)]
qui1 = qui [random.randint(0,len(qui)-1)]
dicton1 = dicton [random.randint(0,len(dicton)-1)]
ou1 = ou [random.randint(0,len(ou)-1)]
principale1 = principale [random.randint(0,len(principale)-1)]

# phrase = exclamation1 + " " + prop_je1 + " " + conclusion1
phrase = qui1 + " " + adj1
print phrase
