#!/bin/bash
# *****************************************************************************
# File          : _MIRROR
# Author        : ALX
# Creation      : 2024-08-25
# Last Revision : 2024-08-25
# Description   : mirror $1 to $2
# *****************************************************************************

#Finir par / (c'est important)
SOURCE="${1}"
DEST="${2}"
LOGDIR=$(basename "$1")
LOG="_MIRRORED"
MESSAGE="mirror ($SOURCE => $DEST)"

if [[ ! -d "${SOURCE}" ]]; then
    echo "ERROR : ${SOURCE} doesn't exist (directory)"
    exit 1
fi

if [[ ! -d "${DEST}" ]]; then
    echo "ERROR : ${DEST} doesn't exist (directory)"
    exit 1
fi

cleanup()
# example cleanup function
{
  echo "Cleaning..."
  return $?
}
 
control_c()
# run if user hits control-c
{
  echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}
 
# trap keyboard interrupt (control-c)
trap control_c SIGINT

ME=`basename "$0"`
DATEBEGIN=$(date)

rsync -avh --size-only --progress --delete "${SOURCE}" "${DEST}"

echo $MESSAGE
echo $ME                     > "${DEST}"/"${LOG}"
echo $MESSAGE               >> "${DEST}"/"${LOG}"
echo "Source : " $SOURCE    >> "${DEST}"/"${LOG}"
echo "Dest   : " $DEST      >> "${DEST}"/"${LOG}"
echo "Begin  : " $DATEBEGIN >> "${DEST}"/"${LOG}"
# echo "SOURCE=${SOURCE}"
# echo "LOG=${LOG}"
# echo "DEST=${DEST}"
# echo "LOGDIR=${LOGDIR}"
DATEEND=$(date)
echo "End    : " $DATEEND   >> "${DEST}"/"${LOG}"

# exit shell script with 0 signal
exit 0
