#!/bin/bash
# Source : https://superuser.com/questions/188493/how-can-i-send-gpg-encrypted-mail-automatically-from-the-linux-command-line
# Send encrypted email
# Requires gpg and mail to be setup

echo "Available keys:"
gpg --list-keys
# Gather variables
echo "Enter public key of recipient:"
read user
echo "Enter email:"
read email
echo "Enter subject:"
read subject
echo "Enter message:"
read message

# Pipe the echoed message to gpg, sign and encrypt it to ascii (-eas), include your key so you can read it,
# include recipients key, pipe to mail with the (unencrypted) subject, send to the given email.
echo "$message" | gpg --no-emit-version -ea -r secure6626@free.fr -r $user
#echo "$message" | gpg2 --no-emit-version -eas -r secure6626@fre.fr -r $user | mail -s "$subject" $email
