#!/bin/bash
if [[ $# -eq 0 ]]; then 
  for FILE in *.webm; do
    echo -e "Processing video '\e[32m$FILE\e[0m'"
    ffmpeg -i "${FILE}" -vn -ab 320k -ar 44100 -y "${FILE%.webm}.mp3"
  done
else
  FILE=$1
  ffmpeg -i "${FILE}" -vn -ab 320k -ar 44100 -y "${FILE%.webm}.mp3"
fi
